## NOTEBOOK CARLOS ANÁLISIS EXPLORATORIO (Seller_name to Price)

In [2]:
import pandas as pd

In [ ]:
df_ini = pd.read_csv('../data/cars.csv')

In [4]:
df_ini

,manufacturer,model,year,mileage,engine,transmission,drivetrain,fuel_type,mpg,exterior_color,interior_color,accidents_or_damage,one_owner,personal_use_only,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
0,Acura,ILX Hybrid 1.5L,2013,92945.0,"1.5L I-4 i-VTEC variable valve control, engine...",Automatic,Front-wheel Drive,Gasoline,39-38,Black,Parchment,0.0,0.0,0.0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0
1,Acura,ILX Hybrid 1.5L,2013,47645.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Gray,Ebony,1.0,1.0,1.0,Kars Today,NaN,4.4,12.0,NaN,17995.0
2,Acura,ILX Hybrid 1.5L,2013,53422.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Bellanova White Pearl,Ebony,0.0,1.0,1.0,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0
3,Acura,ILX Hybrid 1.5L,2013,117598.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,Polished Metal Metallic,NaN,0.0,1.0,1.0,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0
4,Acura,ILX Hybrid 1.5L,2013,114865.0,1.5L I4 8V MPFI SOHC Hybrid,Automatic CVT,Front-wheel Drive,Hybrid,39-38,NaN,Ebony,1.0,0.0,1.0,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762086,Volvo,S60 B5 Momentum,2022,22877.0,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,All-wheel Drive,Gasoline,25-33,Bright Silver Metallic,Blond,0.0,1.0,0.0,Volvo Cars Danbury,4.2,4.2,2.0,250.0,34798.0
762087,Volvo,S60 T5,2012,72900.0,250.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,A/T,Front-wheel Drive,Gasoline,NaN,Red,Beige,NaN,NaN,NaN,NaN,NaN,4.5,101.0,NaN,12500.0
762088,Volvo,S60 T5,2014,92000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,Front-wheel Drive,Gasoline,21-30,Ice White,Soft Beige,0.0,0.0,1.0,Dapper Car Sales,NaN,4.8,36.0,300.0,12299.0
762089,Volvo,S60 T5 Platinum,2013,132000.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Ice White,Off Black,1.0,0.0,0.0,Legend Auto Sales Inc.,4.6,4.7,62.0,1000.0,8995.0
762090,Volvo,S60 T5 Premier,2015,115592.0,2.5L I5 20V MPFI DOHC Turbo,6-Speed Automatic,All-wheel Drive,Gasoline,20-29,Savile Gray Metallic,Off-Black,1.0,0.0,1.0,Plymouth Auto Sales,NaN,4.7,51.0,501.0,12999.0

In [5]:
df_ini.columns

Index(['manufacturer', 'model', 'year', 'mileage', 'engine', 'transmission',
       'drivetrain', 'fuel_type', 'mpg', 'exterior_color', 'interior_color',
       'accidents_or_damage', 'one_owner', 'personal_use_only', 'seller_name',
       'seller_rating', 'driver_rating', 'driver_reviews_num', 'price_drop',
       'price'],
      dtype='object')

In [6]:
columns = ['seller_name', 'seller_rating', 'driver_rating', 'driver_reviews_num', 'price_drop', 'price']
df = df_ini[columns].copy()

In [7]:
df

,seller_name,seller_rating,driver_rating,driver_reviews_num,price_drop,price
0,Iconic Coach,NaN,4.4,12.0,300.0,13988.0
1,Kars Today,NaN,4.4,12.0,NaN,17995.0
2,Weiss Toyota of South County,4.3,4.4,12.0,500.0,17000.0
3,Apple Tree Acura,NaN,4.4,12.0,675.0,14958.0
4,Herb Connolly Chevrolet,3.7,4.4,12.0,300.0,14498.0
...,...,...,...,...,...,...
762086,Volvo Cars Danbury,4.2,4.2,2.0,250.0,34798.0
762087,NaN,NaN,4.5,101.0,NaN,12500.0
762088,Dapper Car Sales,NaN,4.8,36.0,300.0,12299.0
762089,Legend Auto Sales Inc.,4.6,4.7,62.0,1000.0,8995.0
762090,Plymouth Auto Sales,NaN,4.7,51.0,501.0,12999.0

### Seller_name

In [8]:
df['seller_name'].unique()

array(['Iconic Coach', 'Kars Today', 'Weiss Toyota of South County', ...,
       'Volvo Cars of Louisville', 'Smith Volvo Cars',
       'Steingold Volvo Cars'], shape=(18255,), dtype=object)

In [9]:
df['seller_name'].isna().sum()

np.int64(8593)

 Pocos missing, podremos rellenarlos

### Seller_rating

In [10]:
df['seller_rating'].unique()

array([nan, 4.3, 3.7, 2.2, 4.6, 3.3, 3.5, 4.7, 4.5, 4.8, 1.8, 4.2, 3.6,
       3.2, 2.8, 4.9, 2.6, 4.4, 1.6, 2.4, 5. , 3.9, 2.1, 4.1, 1.5, 3.4,
       4. , 3.1, 2.5, 2.9, 3.8, 3. , 2. , 2.3, 1.7, 1.3, 1.4, 2.7, 1.9,
       1. , 1.2, 1.1])

In [11]:
df['seller_rating'].isna().sum()

np.int64(213973)

30% de missings, quizás eliminemos esta columna

### Driver_rating

In [12]:
df['driver_rating'].unique()

array([4.4, 3.7, 5. , 3.8, 4.7, 4.8, 4.1, 4.9, nan, 4. , 4.6, 4.5, 4.3,
       4.2, 1. , 3. , 3.9, 3.5, 3.3, 3.4, 3.2, 2.5, 2.8, 3.6, 3.1, 2.9,
       2. , 1.5, 1.3, 2.3, 2.7, 2.6, 1.9, 2.1, 1.7, 2.2])

In [19]:
df['driver_rating'].isna().sum()

np.int64(31632)

Solo 4% de missing

### Driver_reviews_num

In [13]:
df['driver_reviews_num'].unique()

array([1.200e+01, 7.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 1.700e+01,
       0.000e+00, 5.000e+00, 4.000e+00, 1.400e+01, 8.000e+00, 3.200e+01,
       2.600e+01, 4.400e+01, 2.000e+01, 2.300e+01, 4.700e+01, 3.800e+01,
       4.200e+01, 3.300e+01, 2.700e+01, 9.000e+00, 1.800e+01, 6.000e+00,
       1.000e+01, 1.100e+01, 1.500e+01, 2.900e+01, 6.000e+01, 9.400e+01,
       1.110e+02, 8.100e+01, 6.500e+01, 4.000e+01, 7.100e+01, 9.200e+01,
       6.400e+01, 3.100e+01, 6.900e+01, 9.700e+01, 2.200e+02, 4.300e+01,
       6.100e+01, 8.400e+01, 1.020e+02, 3.600e+01, 7.900e+01, 2.100e+01,
       1.600e+01, 8.500e+01, 5.100e+01, 5.500e+01, 3.400e+01, 4.500e+01,
       4.100e+01, 4.600e+01, 8.300e+01, 5.600e+01, 1.250e+02, 5.400e+01,
       4.900e+01, 1.900e+01, 5.300e+01, 5.200e+01, 1.330e+02, 6.300e+01,
       1.140e+02, 1.130e+02, 6.200e+01, 5.700e+01, 6.800e+01, 7.500e+01,
       7.200e+01, 1.300e+01, 2.800e+01, 2.400e+01, 2.500e+01, 3.500e+01,
       2.200e+01, 9.500e+01, 8.200e+01, 9.000e+01, 5.800e+01, 5.000e+01,
       5.900e+01, 9.800e+01, 3.000e+01, 6.700e+01, 3.700e+01, 1.810e+02,
       7.800e+01, 7.400e+01, 1.200e+02, 8.600e+01, 3.900e+01, 1.000e+02,
       7.000e+01, 1.680e+02, 1.600e+02, 1.180e+02, 2.290e+02, 1.070e+02,
       7.700e+01, 8.900e+01, 8.800e+01, 1.100e+02, 1.460e+02, 9.600e+01,
       1.370e+02, 4.800e+01, 1.310e+02, 6.600e+01, 2.130e+02, 1.240e+02,
       1.830e+02, 1.900e+02, 1.570e+02, 1.280e+02, 8.000e+01, 7.300e+01,
       1.080e+02, 2.010e+02, 1.320e+02, 9.900e+01, 1.120e+02, 1.150e+02,
       7.600e+01, 1.340e+02, 1.090e+02, 1.170e+02, 1.580e+02, 1.750e+02,
       1.710e+02, 2.640e+02, 1.390e+02, 1.940e+02, 1.720e+02, 1.500e+02,
       1.840e+02, 8.700e+01, 1.610e+02, 1.230e+02, 1.010e+02, 1.210e+02,
       1.350e+02, 9.100e+01, 2.680e+02, 2.050e+02, 1.160e+02, 1.030e+02,
       1.050e+02, 1.520e+02, 1.290e+02, 2.060e+02, 1.850e+02, 1.190e+02,
       2.510e+02, 1.060e+02, 2.670e+02, 3.530e+02, 3.160e+02, 1.780e+02,
       2.540e+02, 1.260e+02, 1.730e+02, 2.120e+02, 2.840e+02, 9.300e+01,
       1.920e+02, 1.590e+02, 2.480e+02, 1.620e+02, 4.190e+02, 2.850e+02,
       7.080e+02, 1.990e+02, 2.400e+02, 2.320e+02, 2.800e+02, 2.970e+02,
       2.420e+02, 2.600e+02, 2.190e+02, 3.450e+02, 2.810e+02, 2.260e+02,
       1.410e+02, 2.650e+02, 4.150e+02, 2.160e+02, 1.270e+02, 1.040e+02,
       3.640e+02, 1.400e+02, 3.760e+02, 2.270e+02, 1.740e+02, 2.910e+02,
       1.910e+02, 2.150e+02, 1.540e+02, 1.300e+02, 1.430e+02, 2.340e+02,
       1.510e+02, 1.480e+02, 2.230e+02, 2.020e+02, 1.930e+02, 3.960e+02,
       3.180e+02, 3.950e+02, 2.040e+02, 4.300e+02, 2.990e+02, 8.240e+02,
       2.220e+02, 3.590e+02, 5.730e+02, 3.930e+02, 2.440e+02, 2.630e+02,
       2.460e+02, 2.660e+02, 2.100e+02, 3.660e+02, 1.630e+02, 1.450e+02,
       3.100e+02, 1.960e+02, 1.470e+02, 2.930e+02, 2.380e+02, 1.550e+02,
       2.390e+02, 2.360e+02, 2.960e+02, 2.550e+02, 1.530e+02, 4.750e+02,
       4.630e+02, 2.350e+02, 7.650e+02, 5.860e+02, 2.950e+02, 2.500e+02,
       2.760e+02, 2.300e+02, 1.380e+02, 1.880e+02, 1.560e+02, 1.690e+02,
       1.660e+02, 1.360e+02, 1.220e+02, 2.110e+02, 2.870e+02, 2.000e+02,
       2.250e+02, 3.890e+02, 6.530e+02, 3.110e+02, 1.970e+02, 1.870e+02,
       3.070e+02, 2.490e+02, 1.670e+02, 5.470e+02, 2.530e+02, 3.360e+02,
       7.450e+02, 2.090e+02, 3.400e+02, 2.770e+02, 3.090e+02, 1.770e+02,
       1.025e+03, 5.410e+02, 8.050e+02, 2.740e+02, 3.870e+02, 4.400e+02,
       3.290e+02, 3.610e+02, 2.560e+02, 5.050e+02, 6.400e+02, 3.300e+02,
       3.000e+02, 3.390e+02, 4.440e+02, 2.170e+02, 3.650e+02, 6.280e+02,
       2.070e+02, 2.080e+02, 2.280e+02, 1.800e+02, 3.350e+02, 3.980e+02,
       4.340e+02, 2.210e+02, 3.170e+02, 2.710e+02, 3.220e+02, 3.540e+02,
       1.640e+02, 4.280e+02, 2.920e+02, 4.100e+02, 2.140e+02, 1.790e+02,
       3.580e+02, 3.970e+02, 1.420e+02, 2.580e+02, 4.910e+02, 1.650e+02,
       3.270e+02, 2.730e+02, 3.370e+02, 4.120e+02, 4.600e+02, 2.900e+02,
       5.980e+02, 2.310e+02, 2.620e+02, 3.080e+02, 2.180e+02, 3.740e+02,
       2.370e+02, 2.330e+02, 3.190e+02, 2.590e+02, 4.170e+02, 5.500e+02,
       2.790e+02, 4.780e+02, 5.000e+02, 3.020e+02, 1.980e+02, 1.440e+02,
       1.760e+02, 2.240e+02, 5.080e+02, 3.210e+02, 3.470e+02, 4.460e+02,
       3.680e+02, 3.690e+02, 7.830e+02, 3.130e+02, 4.690e+02, 3.010e+02,
       4.200e+02, 1.860e+02, 3.490e+02, 4.500e+02, 5.910e+02, 7.710e+02,
       1.490e+02, 3.830e+02, 3.340e+02, 1.700e+02, 3.140e+02, 2.410e+02,
       3.910e+02, 2.890e+02, 1.890e+02])

In [14]:
df['driver_reviews_num'].isna().sum()

np.int64(0)

Ningún missing.

### Price

Columna target/etiqueta

In [15]:
df['price'].unique()

array([13988., 17995., 17000., ..., 36328.,  8237.,  4563.],
      shape=(63464,))

In [16]:
df['price'].isna().sum()

np.int64(0)

Ningún missing.

### Price_drop

In [17]:
df['price_drop'].unique()

array([  300.,    nan,   500., ..., 10723.,  4785.,  6920.], shape=(6405,))

In [18]:
df['price_drop'].isna().sum()

np.int64(351979)

46% de missing, quizás nos carguemos esta columna.